// TASK-010: maps the neutral semantic contract to a brand through data-brand and data-theme.
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BLOCKED_PAIRS,
  assembleTokens,
  checkContrast,
  cssVariableName,
  manifest as tokensManifest,
  type TokenManifest,
} from "@klima-ds/tokens/tooling";
import themes from "../themes.json" with { type: "json" };

type Obj = Record<string, unknown>;

export interface BrandTheme {
  /** Sources applied in every mode. */
  shared?: string[];
  /** One source per token mode. */
  modes: Record<string, string>;
}
export interface ThemeManifest {
  brands: Record<string, BrandTheme>;
}
export interface ThemeOverride {
  path: string;
  /** Alias target, such as `brand.sole.indigo.400`. */
  target: string;
}

export const GENERATED_NOTICE =
  "Generated by @klima-ds/themes from DTCG sources. Do not edit; run `pnpm --filter @klima-ds/themes build`.";

const brandName = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;

function defaultRoot(): string {
  return fileURLToPath(new URL("../", import.meta.url));
}
function isObject(value: unknown): value is Obj {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function entries(node: Obj, prefix = ""): [string, Obj][] {
  if (Object.hasOwn(node, "$value") || Object.hasOwn(node, "$ref")) return [[prefix, node]];
  return Object.entries(node).flatMap(([key, child]) =>
    key.startsWith("$") || !isObject(child)
      ? []
      : entries(child, prefix ? `${prefix}.${key}` : key),
  );
}
function tokenAt(document: Obj, path: string): Obj | undefined {
  let current: unknown = document;
  for (const segment of path.split(".")) {
    if (!isObject(current) || !Object.hasOwn(current, segment)) return undefined;
    current = current[segment];
  }
  return isObject(current) && Object.hasOwn(current, "$value") ? current : undefined;
}
function readSource(root: string, path: string): Obj {
  return JSON.parse(readFileSync(resolve(root, path), "utf8")) as Obj;
}

/**
 * Reads and validates the overrides of one brand and mode against the token
 * contract. Throws with every problem found, so an invalid theme never builds.
 */
export function resolveTheme(
  brand: string,
  mode: string,
  input: ThemeManifest = themes as ThemeManifest,
  root = defaultRoot(),
  tokens: TokenManifest = tokensManifest as TokenManifest,
): ThemeOverride[] {
  const theme = input.brands[brand];
  if (!theme) throw new Error(`Unknown brand theme: ${brand}`);
  const modeSource = theme.modes[mode];
  if (!modeSource) throw new Error(`Brand ${brand} does not declare mode ${mode}`);
  const assembled = assembleTokens(tokens, undefined, { mode });
  const problems: string[] = [];
  const overrides: ThemeOverride[] = [];
  const seen = new Set<string>();
  for (const source of [...(theme.shared ?? []), modeSource])
    for (const [path, node] of entries(readSource(root, source))) {
      const where = `${path} (${source})`;
      if (seen.has(path)) problems.push(`${where}: declared twice for mode ${mode}`);
      seen.add(path);
      const contract = tokenAt(assembled.document, path);
      const value = node.$value;
      if (!contract || assembled.layerByPath.get(path) !== "semantic") {
        problems.push(`${where}: themes may only override existing semantic tokens`);
        continue;
      }
      if (node.$type !== contract.$type)
        problems.push(
          `${where}: type ${String(node.$type)} differs from ${String(contract.$type)}`,
        );
      if (typeof value !== "string" || !/^\{[^{}]+\}$/.test(value)) {
        problems.push(`${where}: overrides must alias a primitive`);
        continue;
      }
      const target = value.slice(1, -1);
      const layer = assembled.layerByPath.get(target);
      const targetNode = tokenAt(assembled.document, target);
      if (!targetNode || (layer !== "global" && layer !== "brand"))
        problems.push(`${where}: alias target is not a primitive: ${value}`);
      else if (layer === "brand" && !target.startsWith(`brand.${brand}.`))
        problems.push(`${where}: a brand theme may only use its own brand primitives: ${value}`);
      else if (targetNode.$type !== contract.$type)
        problems.push(`${where}: alias target type ${String(targetNode.$type)} differs`);
      else overrides.push({ path, target });
    }
  if (problems.length === 0) {
    const themed = structuredClone(assembled.document);
    for (const { path, target } of overrides) (tokenAt(themed, path) as Obj).$value = `{${target}}`;
    const blocked = new Set(
      BLOCKED_PAIRS.filter((pair) => pair.modes.includes(mode)).map(
        (pair) => `${pair.foreground} on ${pair.background}`,
      ),
    );
    for (const result of checkContrast(themed))
      if (!result.passes && !blocked.has(`${result.foreground} on ${result.background}`))
        problems.push(
          `${result.foreground} on ${result.background}: ${result.ratio.toFixed(2)} < ${result.minimum} in ${brand} ${mode}`,
        );
  }
  if (problems.length > 0)
    throw new Error(`Invalid ${brand} theme in mode ${mode}:\n- ${problems.join("\n- ")}`);
  return overrides;
}

/** Selector of a brand in one mode; the default mode also applies without data-theme. */
export function themeSelector(brand: string, mode: string, modes: readonly string[]): string {
  const [defaultMode, ...others] = modes;
  if (mode !== defaultMode) return `[data-brand="${brand}"][data-theme="${mode}"]`;
  // Two attribute selectors (0,2,0) outrank the neutral :root and [data-theme] rules (0,1,0)
  // regardless of stylesheet order.
  return `[data-brand="${brand}"]${others.map((other) => `:not([data-theme="${other}"])`).join("")}`;
}

/** Generates `<brand>.css` and its declaration file for every brand. */
export function generateThemes(
  input: ThemeManifest = themes as ThemeManifest,
  root = defaultRoot(),
  tokens: TokenManifest = tokensManifest as TokenManifest,
): Record<string, string> {
  const modes = tokens.modes ?? [];
  const output: Record<string, string> = {};
  for (const [brand, theme] of Object.entries(input.brands)) {
    if (!brandName.test(brand)) throw new Error(`Invalid brand name: ${brand}`);
    const declared = Object.keys(theme.modes);
    if (declared.length !== modes.length || modes.some((mode) => !declared.includes(mode)))
      throw new Error(`Brand ${brand} must declare exactly the token modes: ${modes.join(", ")}`);
    const blocks = modes.map((mode) => {
      const lines = resolveTheme(brand, mode, input, root, tokens).map(
        ({ path, target }) => `  ${cssVariableName(path)}: var(${cssVariableName(target)});`,
      );
      return `${themeSelector(brand, mode, modes)} {\n${lines.join("\n")}\n}\n`;
    });
    output[`${brand}.css`] = `/* ${GENERATED_NOTICE} */\n${blocks.join("\n")}`;
    output[`${brand}.css.d.ts`] = `// ${GENERATED_NOTICE}\nexport {};\n`;
  }
  return output;
}

export interface GeneratedDrift {
  file: string;
  problem: "missing" | "stale";
}

/** Compares a build output directory against what the current sources generate. */
export function checkGenerated(
  outputDir: string,
  artifacts: Record<string, string> = generateThemes(),
): GeneratedDrift[] {
  return Object.entries(artifacts).flatMap(([file, expected]): GeneratedDrift[] => {
    let actual: string;
    try {
      actual = readFileSync(join(outputDir, file), "utf8");
    } catch {
      return [{ file, problem: "missing" }];
    }
    return actual === expected ? [] : [{ file, problem: "stale" }];
  });
}
