import klimaConfig from "@klima-ds/eslint-config";

const nodeGlobals = {
  console: "readonly",
  fetch: "readonly",
  process: "readonly",
  setTimeout: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
};

export default [
  // Site generated by test/build.test.js (Astro types, build output).
  { ignores: [".test-site/**"] },
  ...klimaConfig,
  { files: ["**/*.{js,mjs}"], languageOptions: { globals: nodeGlobals } },
];
