// TASK-009: turns the assembled DTCG documents into deterministic CSS and TypeScript artifacts.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import manifest from "../manifest.json" with { type: "json" };
import { assembleTokens } from "./manifest.js";
import type { TokenManifest } from "./types.js";

type Obj = Record<string, unknown>;
interface FlatToken {
  path: string;
  type: string;
  /** CSS value; aliases become var() references so they follow the active mode. */
  css: string;
  /** Fully resolved CSS value for the mode. */
  resolved: string;
}

export const CSS_PREFIX = "--klima-";
export const GENERATED_NOTICE =
  "Generated by @klima-ds/tokens from DTCG sources. Do not edit; run `pnpm --filter @klima-ds/tokens build`.";

const genericFamilies = new Set([
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui",
  "ui-serif",
  "ui-sans-serif",
  "ui-monospace",
  "ui-rounded",
  "math",
  "emoji",
  "fangsong",
]);
// DTCG 2025.10 named font weights.
const fontWeights: Record<string, number> = {
  thin: 100,
  hairline: 100,
  "extra-light": 200,
  "ultra-light": 200,
  light: 300,
  normal: 400,
  regular: 400,
  book: 400,
  medium: 500,
  "semi-bold": 600,
  "demi-bold": 600,
  bold: 700,
  "extra-bold": 800,
  "ultra-bold": 800,
  black: 900,
  heavy: 900,
  "extra-black": 950,
  "ultra-black": 950,
};
const cssColorFunctionSpaces = new Set([
  "srgb-linear",
  "display-p3",
  "a98-rgb",
  "prophoto-rgb",
  "rec2020",
  "xyz-d65",
  "xyz-d50",
]);

function isObject(value: unknown): value is Obj {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function isAlias(value: unknown): value is string {
  return typeof value === "string" && /^\{[^{}]+\}$/.test(value);
}
function number(value: number): string {
  return String(Number(value.toFixed(4)));
}

export function cssVariableName(path: string): string {
  return `${CSS_PREFIX}${path.replaceAll(".", "-")}`;
}

function serializeColor(value: Obj, path: string): string {
  const components = value.components as number[];
  const alpha = typeof value.alpha === "number" ? value.alpha : 1;
  if (value.colorSpace === "srgb") {
    const channels = [...components, ...(alpha < 1 ? [alpha] : [])];
    return `#${channels
      .map((c) =>
        Math.round(c * 255)
          .toString(16)
          .padStart(2, "0"),
      )
      .join("")}`;
  }
  if (typeof value.colorSpace === "string" && cssColorFunctionSpaces.has(value.colorSpace))
    return `color(${value.colorSpace} ${components.map(number).join(" ")}${alpha < 1 ? ` / ${number(alpha)}` : ""})`;
  throw new Error(`Unsupported color space for CSS output: ${String(value.colorSpace)} (${path})`);
}
function serializeDimension(value: Obj): string {
  return `${number(value.value as number)}${value.unit as string}`;
}
function serializeFontFamily(value: unknown): string {
  const families = Array.isArray(value) ? (value as string[]) : [value as string];
  return families
    .map((family) =>
      genericFamilies.has(family) ? family : `"${family.replaceAll(/["\\]/g, "\\$&")}"`,
    )
    .join(", ");
}

/** Serializes a resolved (literal) DTCG value as a CSS value. */
export function serializeValue(type: string, value: unknown, path: string): string {
  switch (type) {
    case "color":
      return serializeColor(value as Obj, path);
    case "dimension":
      return serializeDimension(value as Obj);
    case "fontFamily":
      return serializeFontFamily(value);
    case "fontWeight":
      return typeof value === "number" ? number(value) : String(fontWeights[value as string]);
    case "number":
      // TASK-005: opacity is authored as an integer from 0 to 100.
      return number(path.startsWith("opacity.") ? (value as number) / 100 : (value as number));
    case "shadow":
      return (Array.isArray(value) ? (value as Obj[]) : [value as Obj])
        .map((shadow) =>
          [
            shadow.inset === true ? "inset" : "",
            serializeDimension(shadow.offsetX as Obj),
            serializeDimension(shadow.offsetY as Obj),
            serializeDimension(shadow.blur as Obj),
            serializeDimension(shadow.spread as Obj),
            serializeColor(shadow.color as Obj, path),
          ]
            .filter(Boolean)
            .join(" "),
        )
        .join(", ");
    default:
      throw new Error(`Token type ${type} has no CSS serialization yet (${path})`);
  }
}

function tokenEntries(node: Obj, prefix = ""): [string, Obj][] {
  if (Object.hasOwn(node, "$value") || Object.hasOwn(node, "$ref")) return [[prefix, node]];
  return Object.entries(node).flatMap(([key, child]) =>
    key.startsWith("$") || !isObject(child)
      ? []
      : tokenEntries(child, prefix ? `${prefix}.${key}` : key),
  );
}
function pointerTarget(ref: string): { path: string; rest: string[] } {
  const parts = ref
    .slice(2)
    .split("/")
    .map((part) => part.replaceAll("~1", "/").replaceAll("~0", "~"));
  const index = parts.indexOf("$value");
  return { path: parts.slice(0, index).join("."), rest: parts.slice(index + 1) };
}

function flatten(document: Obj): FlatToken[] {
  const entries = tokenEntries(document);
  const byPath = new Map(entries);
  const resolve = (path: string): unknown => {
    const node = byPath.get(path);
    if (!node) throw new Error(`Unresolvable token: ${path}`);
    if (Object.hasOwn(node, "$ref")) {
      const target = pointerTarget(node.$ref as string);
      return target.rest.reduce<unknown>(
        (value, key) => (value as Record<string, unknown>)[key],
        resolve(target.path),
      );
    }
    if (isAlias(node.$value)) return resolve(node.$value.slice(1, -1));
    if (node.$type === "typography" && isObject(node.$value))
      return Object.fromEntries(
        Object.entries(node.$value).map(([key, value]) => [
          key,
          isAlias(value) ? resolve(value.slice(1, -1)) : value,
        ]),
      );
    return node.$value;
  };
  return entries.map(([path, node]) => {
    const type = node.$type as string;
    const resolved = serializeValue(type, resolve(path), path);
    let css = resolved;
    if (isAlias(node.$value)) css = `var(${cssVariableName(node.$value.slice(1, -1))})`;
    else if (Object.hasOwn(node, "$ref")) {
      const target = pointerTarget(node.$ref as string);
      if (target.rest.length === 0) css = `var(${cssVariableName(target.path)})`;
    }
    return { path, type, css, resolved };
  });
}

function assertUniqueNames(tokens: FlatToken[]): void {
  const seen = new Map<string, string>();
  for (const { path } of tokens) {
    const name = cssVariableName(path);
    const previous = seen.get(name);
    if (previous)
      throw new Error(`CSS custom property collision: ${previous} and ${path} → ${name}`);
    seen.set(name, path);
  }
}

function css(modes: string[], byMode: Map<string, FlatToken[]>): string {
  const [defaultMode, ...others] = modes;
  const base = byMode.get(defaultMode as string) ?? [];
  const block = (selector: string, tokens: FlatToken[]) =>
    `${selector} {\n${tokens.map((t) => `  ${cssVariableName(t.path)}: ${t.css};`).join("\n")}\n}\n`;
  const blocks = [block(`:root,\n[data-theme="${defaultMode}"]`, base)];
  const baseCss = new Map(base.map((token) => [token.path, token.css]));
  for (const mode of others) {
    const changed = (byMode.get(mode) ?? []).filter((t) => baseCss.get(t.path) !== t.css);
    blocks.push(block(`[data-theme="${mode}"]`, changed));
  }
  return `/* ${GENERATED_NOTICE} */\n${blocks.join("\n")}`;
}

function nest(tokens: FlatToken[], leaf: (token: FlatToken) => string): Obj {
  const root: Obj = {};
  for (const token of tokens) {
    const parts = token.path.split(".");
    let node = root;
    for (const part of parts.slice(0, -1)) node = (node[part] ??= {}) as Obj;
    node[parts.at(-1) as string] = leaf(token);
  }
  return root;
}
function literal(value: unknown, indent: string, typed: boolean): string {
  if (typeof value === "string") return JSON.stringify(value);
  const inner = `${indent}  `;
  const entries = Object.entries(value as Obj).map(
    ([key, child]) =>
      `${inner}${typed ? "readonly " : ""}${JSON.stringify(key)}: ${literal(child, inner, typed)}${typed ? ";" : ","}`,
  );
  return `{\n${entries.join("\n")}\n${indent}}`;
}

function javascript(modes: string[], byMode: Map<string, FlatToken[]>): string {
  const base = byMode.get(modes[0] as string) ?? [];
  const values = Object.fromEntries(
    modes.map((mode) => [
      mode,
      Object.fromEntries((byMode.get(mode) ?? []).map((t) => [t.path, t.resolved])),
    ]),
  );
  return [
    `// ${GENERATED_NOTICE}`,
    `export const modes = ${JSON.stringify(modes)};`,
    `export const defaultMode = ${JSON.stringify(modes[0])};`,
    `export const cssVariables = ${literal(Object.fromEntries(base.map((t) => [t.path, cssVariableName(t.path)])), "", false)};`,
    `export const tokens = ${literal(
      nest(base, (t) => `var(${cssVariableName(t.path)})`),
      "",
      false,
    )};`,
    `export const values = ${literal(values, "", false)};`,
    "",
  ].join("\n");
}

function declarations(modes: string[], byMode: Map<string, FlatToken[]>): string {
  const base = byMode.get(modes[0] as string) ?? [];
  return [
    `// ${GENERATED_NOTICE}`,
    `/** Color schemes; the first one is applied by default on :root. */`,
    `export type Mode = ${modes.map((mode) => JSON.stringify(mode)).join(" | ")};`,
    `/** Logical path of every token, such as "color.text.primary". */`,
    `export type TokenPath =\n${base.map((t) => `  | ${JSON.stringify(t.path)}`).join("\n")};`,
    `export declare const modes: readonly [${modes.map((mode) => JSON.stringify(mode)).join(", ")}];`,
    `export declare const defaultMode: ${JSON.stringify(modes[0])};`,
    `/** CSS custom property name of each token. */`,
    `export declare const cssVariables: ${literal(Object.fromEntries(base.map((t) => [t.path, cssVariableName(t.path)])), "", true)};`,
    `/** Nested var() references that follow the active mode. */`,
    `export declare const tokens: ${literal(
      nest(base, (t) => `var(${cssVariableName(t.path)})`),
      "",
      true,
    )};`,
    `/** Fully resolved CSS values per mode, for contexts without CSS custom properties. */`,
    `export declare const values: { readonly [M in Mode]: { readonly [P in TokenPath]: string } };`,
    "",
  ].join("\n");
}

/**
 * Generates every artifact as a map from its path inside `dist/` to its exact
 * content. The output depends only on the token sources.
 */
export function generateArtifacts(
  input: TokenManifest = manifest as TokenManifest,
  root?: string,
): Record<string, string> {
  const modes = input.modes && input.modes.length > 0 ? input.modes : ["default"];
  const byMode = new Map<string, FlatToken[]>();
  for (const mode of modes) {
    const assembled = assembleTokens(input, root, input.modes ? { mode } : {});
    if (!assembled.validation.valid)
      throw new Error(
        `Token sources are invalid in mode ${mode}: ${assembled.validation.diagnostics
          .map((d) => `${d.code} ${d.path}`)
          .join(", ")}`,
      );
    const tokens = flatten(assembled.document);
    assertUniqueNames(tokens);
    byMode.set(mode, tokens);
  }
  const paths = (mode: string) => (byMode.get(mode) ?? []).map((t) => t.path).join("\n");
  for (const mode of modes.slice(1))
    if (paths(mode) !== paths(modes[0] as string))
      throw new Error(`Mode ${mode} does not expose the same tokens as ${modes[0]}`);
  return {
    "tokens.css": css(modes, byMode),
    "tokens.css.d.ts": `// ${GENERATED_NOTICE}\nexport {};\n`,
    "index.js": javascript(modes, byMode),
    "index.d.ts": declarations(modes, byMode),
  };
}

export interface GeneratedDrift {
  file: string;
  problem: "missing" | "stale";
}

/** Compares a build output directory against what the current sources generate. */
export function checkGenerated(
  outputDir: string,
  artifacts: Record<string, string> = generateArtifacts(),
): GeneratedDrift[] {
  const drift: GeneratedDrift[] = [];
  for (const [file, expected] of Object.entries(artifacts)) {
    let actual: string;
    try {
      actual = readFileSync(join(outputDir, file), "utf8");
    } catch {
      drift.push({ file, problem: "missing" });
      continue;
    }
    if (actual !== expected) drift.push({ file, problem: "stale" });
  }
  return drift;
}
