import type { IconStyle } from "./naming.js";
import type { IconNode } from "./normalize.js";

export const GENERATED_HEADER = "// Generated by @klima-ds/icons-core. Do not edit.\n";

export interface GeneratedIcon {
  /** Kebab-case file and subpath name, e.g. `search-normal`. */
  name: string;
  /** Exported component name, e.g. `SearchNormal`. */
  component: string;
  /** Normalized root `<svg>` node. */
  node: IconNode;
}

export interface GeneratedStyle {
  style: IconStyle;
  icons: readonly GeneratedIcon[];
}

const ROOT_ATTRIBUTES = new Set(["viewBox", "fill", "stroke", "xmlns"]);

/** Fails on SVG features the framework generators cannot express safely. */
export function assertSupportedIcon(node: IconNode, file: string): void {
  const unexpected = Object.keys(node.attrs).filter(
    (name) => !ROOT_ATTRIBUTES.has(name) && !name.startsWith("xmlns:"),
  );
  if (unexpected.length > 0)
    throw new Error(`${file}: unsupported root attributes: ${unexpected.join(", ")}`);
  const visit = (current: IconNode) => {
    if (Object.hasOwn(current.attrs, "style"))
      throw new Error(`${file}: inline style attributes are not supported in icon sources`);
    current.children.forEach(visit);
  };
  visit(node);
}

/** Root attributes that every generated component applies before consumer props. */
export function rootDefaults(node: IconNode): Record<string, string> {
  return Object.fromEntries(
    Object.entries(node.attrs).filter(([name]) => !name.startsWith("xmlns:")),
  );
}

/** Icons of a style sorted by name; rejects component names that would collide. */
export function sortedIcons({ style, icons }: GeneratedStyle): GeneratedIcon[] {
  const sorted = [...icons].sort((a, b) => a.name.localeCompare(b.name));
  const seen = new Set<string>();
  for (const icon of sorted) {
    if (seen.has(icon.component))
      throw new Error(`${style}/${icon.name}: duplicate component name ${icon.component}`);
    seen.add(icon.component);
  }
  return sorted;
}
