import type { IconNode } from "./normalize.js";
import type { IconStyle } from "./naming.js";

export interface GeneratedIcon {
  /** Kebab-case file and subpath name, e.g. `search-normal`. */
  name: string;
  /** Exported component name, e.g. `SearchNormal`. */
  component: string;
  /** Normalized root `<svg>` node. */
  node: IconNode;
}

export interface GeneratedStyle {
  style: IconStyle;
  icons: readonly GeneratedIcon[];
}

/** Compact element tuple consumed by the runtime: [tag, attributes, children?]. */
type NodeTuple = [string, Record<string, string>, NodeTuple[]?];

const HEADER = "// Generated by @klima-ds/icons-core. Do not edit.\n";
const ROOT_ATTRIBUTES = new Set(["viewBox", "fill", "stroke", "xmlns"]);
const SPECIAL_ATTRIBUTES: Readonly<Record<string, string>> = {
  class: "className",
  "xlink:href": "xlinkHref",
  "xml:space": "xmlSpace",
};

/** Converts SVG attribute names to React props; `aria-*` and `data-*` stay kebab-case. */
export function reactAttributeName(name: string): string {
  if (SPECIAL_ATTRIBUTES[name]) return SPECIAL_ATTRIBUTES[name];
  if (name.startsWith("aria-") || name.startsWith("data-")) return name;
  return name.replace(/[-:]([a-z])/g, (_, letter: string) => letter.toUpperCase());
}

function reactAttributes(attrs: Record<string, string>, file: string): Record<string, string> {
  const output: Record<string, string> = {};
  for (const [name, value] of Object.entries(attrs)) {
    if (name === "style")
      throw new Error(`${file}: inline style attributes are not supported in icon sources`);
    if (name.startsWith("xmlns:")) continue;
    output[reactAttributeName(name)] = value;
  }
  return output;
}

function toTuple(node: IconNode, file: string): NodeTuple {
  const attrs = reactAttributes(node.attrs, file);
  return node.children.length > 0
    ? [node.tag, attrs, node.children.map((child) => toTuple(child, file))]
    : [node.tag, attrs];
}

function rootAttributes(node: IconNode, file: string): Record<string, string> {
  const unexpected = Object.keys(node.attrs).filter(
    (name) => !ROOT_ATTRIBUTES.has(name) && !name.startsWith("xmlns:"),
  );
  if (unexpected.length > 0)
    throw new Error(`${file}: unsupported root attributes: ${unexpected.join(", ")}`);
  return reactAttributes(node.attrs, file);
}

const RUNTIME_JS = `${HEADER}import { createElement, forwardRef, useId } from "react";

function renderNode(node, key) {
  const [tag, attrs, children] = node;
  return createElement(tag, { key, ...attrs }, children ? children.map(renderNode) : undefined);
}

export function createIcon(displayName, rootAttrs, nodes) {
  const Icon = forwardRef(function Icon({ size = 24, title, children, ...props }, ref) {
    const titleId = useId();
    const accessibility = title
      ? { role: "img", "aria-labelledby": titleId }
      : { "aria-hidden": true, focusable: "false" };
    return createElement(
      "svg",
      { ...rootAttrs, width: size, height: size, ...accessibility, ...props, ref },
      title ? createElement("title", { id: titleId }, title) : null,
      nodes.map(renderNode),
      children,
    );
  });
  Icon.displayName = displayName;
  return Icon;
}
`;

const RUNTIME_DTS = `${HEADER}import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from "react";

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, "ref"> {
  /** Width and height of the icon. Defaults to 24. */
  size?: number | string;
  /** Accessible name. Without a title the icon is decorative and hidden from assistive technology. */
  title?: string;
}

export type IconComponent = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>;

/** @internal */
export declare function createIcon(
  displayName: string,
  rootAttrs: Record<string, string>,
  nodes: readonly unknown[],
): IconComponent;
`;

/** Returns the generated package files keyed by path relative to the output directory. */
export function renderReact(styles: readonly GeneratedStyle[]): Map<string, string> {
  const files = new Map<string, string>([
    ["create-icon.js", RUNTIME_JS],
    ["create-icon.d.ts", RUNTIME_DTS],
  ]);
  for (const { style, icons } of styles) {
    const sorted = [...icons].sort((a, b) => a.name.localeCompare(b.name));
    const seen = new Set<string>();
    for (const icon of sorted) {
      if (seen.has(icon.component))
        throw new Error(`${style}/${icon.name}: duplicate component name ${icon.component}`);
      seen.add(icon.component);
      const file = `${style}/${icon.name}`;
      const root = rootAttributes(icon.node, file);
      const nodes = icon.node.children.map((child) => toTuple(child, file));
      files.set(
        `${file}.js`,
        `${HEADER}import { createIcon } from "../create-icon.js";\n\n` +
          `const ${icon.component} = /* @__PURE__ */ createIcon(${JSON.stringify(icon.component)}, ${JSON.stringify(root)}, ${JSON.stringify(nodes)});\n\n` +
          `export default ${icon.component};\nexport { ${icon.component} };\n`,
      );
      files.set(
        `${file}.d.ts`,
        `${HEADER}import type { IconComponent } from "../create-icon.js";\n\n` +
          `declare const ${icon.component}: IconComponent;\n\n` +
          `export default ${icon.component};\nexport { ${icon.component} };\n`,
      );
    }
    const reexports = sorted
      .map((icon) => `export { ${icon.component} } from "./${icon.name}.js";\n`)
      .join("");
    files.set(`${style}/index.js`, `${HEADER}${reexports}`);
    files.set(
      `${style}/index.d.ts`,
      `${HEADER}export type { IconComponent, IconProps } from "../create-icon.js";\n${reexports}`,
    );
  }
  return files;
}
